[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "iplz"
version = "0.0.1"
#dependencies = [
#    "falcon"
#]

[tool.setuptools.packages]
find = {}  # Scanning implicit namespaces is active by default